import { ResourcePermissions, TokenPermissions } from '@kyso-io/kyso-model';
import { logoutAction, selectCurrentUserPermissions } from '@kyso-io/kyso-store';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import { useAppDispatch, useAppSelector } from '../hooks/redux-hooks';
import { useAuth } from '../hooks/auth';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  useAuth();
  const router = useRouter();
  const dispatch = useAppDispatch();
  const permissions: TokenPermissions | null = useAppSelector(selectCurrentUserPermissions);

  if (!permissions) {
    return <div />;
  }

  const logout = async () => {
    await dispatch(logoutAction());
    localStorage.removeItem('jwt');
    router.push('/login');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {permissions.organizations!.map((organization: ResourcePermissions) => (
          <Link key={organization.id} href={`/${organization.name}`}>
            {organization.display_name}
          </Link>
        ))}
        <Link href="/login">Login</Link>
        <button onClick={logout}>Logout</button>
      </main>
    </div>
  );
};

export default Home;
